"""本机 uv 单环境安装向导：探测/确认 GPU，写入 .install_profile，再 uv sync。"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


BOOTUP = Path(__file__).resolve().parent
ROOT = BOOTUP.parent
PROFILE_PATH = BOOTUP / ".install_profile"
VENV_DIR = BOOTUP / ".venv"
UV_INSTALL_HINT = (
    "Install uv first, then re-run:\n"
    '  powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"\n'
    "  https://docs.astral.sh/uv/getting-started/installation/"
)


def _run(cmd: list[str], *, cwd: Path | None = None) -> int:
    """
    函数名: _run
    作用: 打印并执行子进程命令
    输入:
        cmd (list[str]): 命令参数列表
        cwd (Path | None): 工作目录，默认 bootup（含 pyproject.toml）
    输出:
        int: 进程退出码
    """
    print(f">>> {' '.join(cmd)}", flush=True)
    return subprocess.call(cmd, cwd=str(cwd or BOOTUP))


def _uv_bin() -> str | None:
    """
    函数名: _uv_bin
    作用: 查找 PATH 中的 uv 可执行文件
    输入: 无
    输出:
        str | None: uv 路径，未找到则为 None
    """
    return shutil.which("uv")


def _venv_python() -> Path | None:
    """
    函数名: _venv_python
    作用: 定位 bootup/.venv 中的 Python 可执行文件
    输入: 无
    输出:
        Path | None: 存在则返回路径，否则 None
    """
    py = VENV_DIR / "Scripts" / "python.exe"
    if py.is_file():
        return py
    py = VENV_DIR / "bin" / "python"
    if py.is_file():
        return py
    return None


def _read_profile() -> dict[str, str]:
    """
    函数名: _read_profile
    作用: 读取 bootup/.install_profile（key=value）；兼容迁移根目录旧文件
    输入: 无
    输出:
        dict[str, str]: 配置项；文件不存在则为空 dict
    """
    legacy = ROOT / ".install_profile"
    if legacy.is_file() and not PROFILE_PATH.is_file():
        PROFILE_PATH.write_text(legacy.read_text(encoding="utf-8"), encoding="utf-8")
        legacy.unlink()
    if not PROFILE_PATH.is_file():
        return {}
    out: dict[str, str] = {}
    for line in PROFILE_PATH.read_text(encoding="utf-8").splitlines():
        text = line.strip()
        if not text or text.startswith("#") or "=" not in text:
            continue
        key, _, val = text.partition("=")
        out[key.strip()] = val.strip()
    return out


def _write_profile(*, accelerator: str, ocr: bool) -> None:
    """
    函数名: _write_profile
    作用: 持久化安装档位到 bootup/.install_profile
    输入:
        accelerator (str): cpu 或 gpu
        ocr (bool): 是否安装 OCR extra
    输出: 无
    """
    body = (
        f"# Generated by bootup/bootstrap_install.py\n"
        f"accelerator={accelerator}\n"
        f"ocr={'true' if ocr else 'false'}\n"
    )
    PROFILE_PATH.write_text(body, encoding="utf-8")
    print(f"Wrote {PROFILE_PATH}", flush=True)


def _detect_gpu() -> bool:
    """
    函数名: _detect_gpu
    作用: 复用 paddle_ocr 硬件探测；探测失败时视为无 GPU
    输入: 无
    输出:
        bool: 本机是否有 NVIDIA GPU
    """
    sys.path.insert(0, str(ROOT))
    try:
        from paddle_ocr.gate.hardware_probe import detect_gpu_hardware
        return bool(detect_gpu_hardware())
    except Exception as exc:
        print(f"GPU probe skipped ({exc}); assuming no NVIDIA GPU.", flush=True)
        return False


def _resolve_accelerator(args: argparse.Namespace, detected: bool) -> str:
    """
    函数名: _resolve_accelerator
    作用: 按 CLI / 已有 profile / 交互确认选定 cpu|gpu
    输入:
        args (Namespace): 解析后的命令行参数
        detected (bool): 硬件探测结果
    输出:
        str: cpu 或 gpu
    """
    if args.gpu:
        return "gpu"
    if args.cpu:
        return "cpu"
    existing = _read_profile()
    if existing.get("accelerator") in ("cpu", "gpu") and not args.force_profile:
        prev = existing["accelerator"]
        print(f"Reusing .install_profile accelerator={prev} (pass --force-profile to re-ask).", flush=True)
        return prev
    print(f"NVIDIA GPU detected: {'yes' if detected else 'no'}", flush=True)
    if not sys.stdin.isatty():
        choice = "gpu" if detected else "cpu"
        print(f"Non-interactive stdin; selecting accelerator={choice}.", flush=True)
        return choice
    default = "Y" if detected else "N"
    if detected:
        prompt = (
            "Install GPU OCR stack (paddlepaddle-gpu / VL)? "
            f"Recommended based on probe: GPU [{default}/n]: "
        )
    else:
        prompt = "No NVIDIA GPU detected. Force GPU OCR stack anyway? [y/N]: "
    raw = input(prompt).strip().lower()
    if not raw:
        return "gpu" if detected else "cpu"
    if raw in ("y", "yes"):
        return "gpu"
    if raw in ("n", "no"):
        return "cpu"
    print(f"Unrecognized answer {raw!r}; using {'gpu' if detected else 'cpu'}.", flush=True)
    return "gpu" if detected else "cpu"


def _ensure_venv(uv: str, python: str | None) -> int:
    """
    函数名: _ensure_venv
    作用: 在 bootup/.venv 创建 uv 虚拟环境
    输入:
        uv (str): uv 可执行路径
        python (str | None): 指定解释器，如 3.10；None 则让 uv 自选
    输出:
        int: 退出码
    """
    cmd = [uv, "venv", str(VENV_DIR)]
    if python:
        cmd.extend(["--python", python])
    return _run(cmd)


def _sync(uv: str, *, accelerator: str, ocr: bool, frozen: bool) -> int:
    """
    函数名: _sync
    作用: 在 bootup 目录 uv sync 安装 core+llm，按需互斥安装 ocr 或 ocr-gpu
    输入:
        uv (str): uv 路径
        accelerator (str): cpu|gpu
        ocr (bool): 是否装 OCR
        frozen (bool): 是否 --frozen
    输出:
        int: 退出码
    """
    cmd = [uv, "sync", "--extra", "llm"]
    if frozen:
        cmd.append("--frozen")
    if ocr:
        if accelerator == "gpu":
            cmd.extend(["--extra", "ocr-gpu"])
        else:
            cmd.extend(["--extra", "ocr"])
    return _run(cmd)


def _post_ocr(accelerator: str) -> int:
    """
    函数名: _post_ocr
    作用: GPU 走 install_backend（VL 预热）；CPU 走 prune；再跑 OCR 门禁
    输入:
        accelerator (str): cpu|gpu
    输出:
        int: 门禁退出码（库安装失败则提前返回）
    """
    backend = ROOT / "paddle_ocr" / "scripts" / "install_backend.py"
    venv_py = _venv_python()
    python = str(venv_py) if venv_py is not None else sys.executable
    # GPU：确保无 CPU 包残留并预热 VL；CPU：prune VL
    rc = _run([python, str(backend), accelerator], cwd=ROOT)
    if rc != 0:
        print(f"WARNING: install_backend ({accelerator}) exited {rc}", flush=True)
    log_dir = ROOT / "temp"
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / "install_paddle_ocr.log"
    print(f"Running OCR CLI gate -> {log_path}", flush=True)
    with log_path.open("a", encoding="utf-8") as logf:
        gate = subprocess.call(
            [python, str(ROOT / "paddle_ocr" / "main.py")],
            cwd=str(ROOT),
            stdout=logf,
            stderr=subprocess.STDOUT,
        )
    if gate != 0:
        print(f"WARNING: OCR CLI gate failed (exit {gate}). See {log_path}", flush=True)
    else:
        print("OCR CLI gate passed.", flush=True)
    return gate


def _ensure_runtime_dirs() -> None:
    """
    函数名: _ensure_runtime_dirs
    作用: 创建 temp / exports / models/gemma4
    输入: 无
    输出: 无
    """
    (ROOT / "temp").mkdir(parents=True, exist_ok=True)
    (ROOT / "exports").mkdir(parents=True, exist_ok=True)
    (ROOT / "models" / "gemma4").mkdir(parents=True, exist_ok=True)


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """
    函数名: _parse_args
    作用: 解析安装向导 CLI
    输入:
        argv (list[str] | None): 参数列表
    输出:
        Namespace: 解析结果
    """
    p = argparse.ArgumentParser(description="uv single-venv bootstrap for excel-template-viz")
    p.add_argument("--skip-ocr", action="store_true", help="Skip OCR extras and OCR gate")
    p.add_argument("--gpu", action="store_true", help="Force GPU OCR stack (ocr-gpu)")
    p.add_argument("--cpu", action="store_true", help="Force CPU OCR stack (ocr)")
    p.add_argument("--force-profile", action="store_true", help="Ignore existing .install_profile prompts")
    p.add_argument("--python", default=None, help="Python version/path for uv venv (e.g. 3.10)")
    p.add_argument("--frozen", action="store_true", help="uv sync --frozen (CI / reproducible)")
    p.add_argument("--no-venv", action="store_true", help="Skip uv venv; only sync into existing env")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """
    函数名: main
    作用: 执行本机 uv 安装向导主流程
    输入:
        argv (list[str] | None): CLI 参数
    输出:
        int: 进程退出码
    """
    args = _parse_args(argv)
    if args.gpu and args.cpu:
        print("ERROR: pass only one of --gpu / --cpu", flush=True)
        return 2
    uv = _uv_bin()
    if not uv:
        print("ERROR: uv not found on PATH.", flush=True)
        print(UV_INSTALL_HINT, flush=True)
        return 1
    print(f"Using uv: {uv}", flush=True)
    if not args.no_venv:
        rc = _ensure_venv(uv, args.python)
        if rc != 0:
            print("ERROR: uv venv failed", flush=True)
            return rc
    detected = _detect_gpu()
    accelerator = _resolve_accelerator(args, detected)
    ocr = not args.skip_ocr
    existing = _read_profile()
    if args.skip_ocr:
        ocr = False
    elif existing.get("ocr") == "false" and not args.force_profile and not args.gpu and not args.cpu:
        ocr = False
        print("Reusing .install_profile ocr=false.", flush=True)
    _write_profile(accelerator=accelerator, ocr=ocr)
    print(f"Profile: accelerator={accelerator} ocr={ocr}", flush=True)
    rc = _sync(uv, accelerator=accelerator, ocr=ocr, frozen=args.frozen)
    if rc != 0:
        print("ERROR: uv sync failed", flush=True)
        return rc
    venv_py = _venv_python()
    python = str(venv_py) if venv_py is not None else sys.executable
    smoke = _run([python, "-c", "import litert_lm; print('litert-lm OK')"], cwd=ROOT)
    if smoke != 0:
        print("ERROR: litert-lm import failed after sync", flush=True)
        return smoke
    if ocr:
        _post_ocr(accelerator)
    _ensure_runtime_dirs()
    print(
        "Installation completed. Start with .\\run.ps1 or: "
        "uv run --project bootup python -m nicegui_ui.app",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
